version: '2'
services:
    blog-app:
        image: blog
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger,zipkin'
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - 'SPRING_DATASOURCE_URL=jdbc:postgresql://blog-postgresql:5432/blog'
            - SECURITY_OAUTH2_CLIENT_CLIENT_ID=${OIDC_CLIENT_ID}
            - SECURITY_OAUTH2_CLIENT_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
            - 'SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=${RESOURCE_USER_INFO_URI}'
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
    blog-postgresql:
        image: 'postgres:10.4'
        environment:
            - POSTGRES_USER=blog
            - POSTGRES_PASSWORD=
    
    gateway-app:
        image: gateway
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger,zipkin'
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - 'SPRING_DATASOURCE_URL=jdbc:postgresql://gateway-postgresql:5432/gateway'
            - 'SECURITY_OAUTH2_CLIENT_ACCESS_TOKEN_URI=${ACCESS_TOKEN_URI}'
            - 'SECURITY_OAUTH2_CLIENT_USER_AUTHORIZATION_URI=${USER_AUTHORIZATION_URI}'
            - SECURITY_OAUTH2_CLIENT_CLIENT_ID=${OIDC_CLIENT_ID}
            - SECURITY_OAUTH2_CLIENT_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
            - SECURITY_OAUTH2_CLIENT_SCOPE=openid profile email
            - 'SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=${RESOURCE_USER_INFO_URI}'
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
        ports:
            - '8080:8080'
    gateway-postgresql:
        image: 'postgres:10.4'
        environment:
            - POSTGRES_USER=gateway
            - POSTGRES_PASSWORD=
    
    store-app:
        image: store
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger,zipkin'
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - 'SPRING_DATA_MONGODB_URI=mongodb://store-mongodb:27017'
            - SPRING_DATA_MONGODB_DATABASE=store
            - SECURITY_OAUTH2_CLIENT_CLIENT_ID=${OIDC_CLIENT_ID}
            - SECURITY_OAUTH2_CLIENT_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
            - 'SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=${RESOURCE_USER_INFO_URI}'
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
    store-mongodb:
        image: 'mongo:4.0.2'
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry

    jhipster-elasticsearch:
        extends:
            file: jhipster-console.yml
            service: jhipster-elasticsearch
    jhipster-logstash:
        extends:
            file: jhipster-console.yml
            service: jhipster-logstash
        depends_on:
            - jhipster-elasticsearch
    jhipster-console:
        extends:
            file: jhipster-console.yml
            service: jhipster-console
        depends_on:
            - jhipster-elasticsearch
    jhipster-import-dashboards:
        extends:
            file: jhipster-console.yml
            service: jhipster-import-dashboards
        depends_on:
            - jhipster-elasticsearch
    jhipster-zipkin:
        extends:
            file: jhipster-console.yml
            service: jhipster-zipkin
        depends_on:
            - jhipster-elasticsearch
    keycloak:
        extends:
            file: keycloak.yml
            service: keycloak
